"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
b = ["bookmark"]
bcr = ["bookmark", "create", "--revision"]
bl = ["bookmark", "list"]
df = ["diff"]
hop = [
  "bookmark",
  "move",
  "--from",
  "closest_bookmark(@)",
  "--to",
  "closest_pushable(@)",
]
l = ["log"]
la = ["log", "-r", "all"]
n = ["new"]
d = ["describe"]
cm = ["commit"]
ab = ["abandon"]
e = ["edit"]
ol = ["op", "log"]
fetch = ["git", "fetch"]
push = ["git", "push"]
sq = ["squash"]

[git]
sign-on-push = true
write-change-id-header = true

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'
'all' = 'all()'

[signing]
behavior = "drop"
backend = "gpg"

[ui]
default-command = "log"
diff-editor = ":builtin"
graph.style = "square"
log-synthetic-elided-nodes = true
pager = "less -FRX"

[user]
name = "nubiv"
email = "h.horace0921@gmail.com"
